sudo: false
language: node_js
node_js:
  - 13.13.0
cache:
  directories:
    - node_modules

branches:
  only:
    - hexo

#在构建之前安装hexo环境
before_install:
  - export  TZ='Asia/Shanghai'
  - npm install -g hexo-cli

#安装 git 插件和搜索功能插件
install:
  - npm install

script:
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public

notifications:
  email:
    - loserkid@163.com
  on_success: change
  on_failure: always